# This is a basic workflow to help you get started with Actions
name: first

concurrency:
  group: ${{ github.ref }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_call:
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.build.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.build.outputs.output2 }}
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first:
    uses: ./.github/workflows/first.yaml
  
  build:
    needs: first
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - run: echo ${{ needs.first.outputs.firstword }} ${{ needs.first.outputs.secondword }}
      - id: step1
        run: echo "firstword=foo" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=bar" >> $GITHUB_OUTPUT